import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/home/header/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <div>{children}</div>
      </body>
    </html>
  );
}
